collections_dir: ./site

port: 10101

title: 欧雷流
description: 我叫欧雷，是一个出生于上世纪 80 年代的理想主义叛逆青年。喜欢日本，热爱咖啡，善于总结。这里有我对技术和语言的研究，也有对世界和生活的思考。
keywords: 欧雷,欧雷流,黑客,软件工程师,前端工程师,前端开发,前端工程,日本,日语,日本文化,个人风格,博客,日记,思考,ourai,ourairyu
tagline: 不走寻常路

collections:
  pages:
    output: true
    permalink: /:path/

# YAML frontmatter
defaults:
  # 默认
  - scope:
      path: ""
    values:
      layout: default
  # 页面
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  # 文章
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      css:
        - pages/post
      js:
        - initializers/time
        - initializers/lazyload
      author:
        name: 欧雷
        email: ourairyu@gmail.com
        uri: https://ourai.ws/
        slug: ourai
        twitter: ourairyu
      siblings: true
      comments: true



# =====
# Plugin-specific configurations
# =====

# Jekyll Feed
feed:
  path: atom.xml
name: 欧雷流
author:
  name: 欧雷
  email: ourairyu@gmail.com
  uri: https://ourai.ws/
  twitter: ourairyu
github:
  url: https://ourai.ws



# Handling Reading
exclude:
  - .asset-cache
  - .sass-cache
  - .vscode
  - node_modules
  - build
  - vendors
  - src
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - Gruntfile.coffee
  - bower.json
  - package.json
  - package-lock.json
  - CNAME
  # - README.md
encoding: utf-8

# Plugins
gems:
  - jekyll-assets
  - jekyll-archives
  - jekyll-feed
  - jekyll-contentblocks
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll/tagging
  - jekyll-tagging-related_posts
  - jekyll_version_plugin

# Conversion
markdown: kramdown
highlighter: pygments

# Outputting
permalink: /posts/:title/
timezone: Asia/Shanghai



# =====
# Plugin-specific configurations
# =====

# Jekyll Archives
# https://github.com/jekyll/jekyll-archives
jekyll-archives:
  enabled:
    - categories
    # - tags
    - year
  layouts:
    category: archive/category
    # tag: classified/tags
    year: archive/year
  permalinks:
    category: "/categories/:name/"
    # tag: "/tags/:name/"
    year: "/archives/:year/"
